### ISSUE TITLE
SCJMapper 2.48.0.83 Show Options Dialogue does not show bindings T16000 FCS HOTAS

### ISSUE THREAD

**Issue by iNgeon** [SCToolsfactory/SCJMapper-V2#105]
Configured my Thrustmaster setup.
There are certain bindings that does not seem to pull through to the Options Dialogue.
As example i am trying to set deadzone on my Throttle forward / back - js2_z but even though it is bound it does not display. 
This is but one that does not pull through.
Please find attached xml and screenshots

[layout_my_joystick_3.12.0_ingeon02g.xml.txt](https://github.com/SCToolsfactory/SCJMapper-V2/files/5939203/layout_my_joystick_3.12.0_ingeon02g.xml.txt)
![MWSnap 2021-02-07, 16_45_41](https://user-images.githubusercontent.com/3817692/107150069-ac1a8f80-6964-11eb-862c-07d598287ec7.jpg)
![MWSnap 2021-02-07, 16_45_55](https://user-images.githubusercontent.com/3817692/107150071-ae7ce980-6964-11eb-8887-4c76bf3bbd64.jpg)
![MWSnap 2021-02-07, 16_46_02](https://user-images.githubusercontent.com/3817692/107150072-afae1680-6964-11eb-88f7-f5d01b5fac3f.jpg)
![MWSnap 2021-02-07, 16_46_13](https://user-images.githubusercontent.com/3817692/107150073-b177da00-6964-11eb-9af7-85f9185b2e5f.jpg)
![MWSnap 2021-02-07, 16_46_17](https://user-images.githubusercontent.com/3817692/107150075-b2a90700-6964-11eb-98ef-1774462fc0e4.jpg)

**Comment by bm98** [comment]
Hi, could be related to an old issue I just found recently. 
Attached is a pre-prelelease of it. 
You may want to backup (zip or so) the current files before copying this patch and overwriting the current ones.
Note the package does not contain all graphics and layouts - only updated ones since Dec last year.
It will therefore not work as standalone - must be copied into the existing folder.
Let me know if this fixes the issue.
(I had to update two libraries due to Github security advise - so some new dll files were added in this process)

[SCJMapper-V2.49Build84-part.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/5947083/SCJMapper-V2.49Build84-part.zip)

**Comment by bm98** [comment]
Consolidated in build 2.50 incl PTU 3.13..
