### ISSUE TITLE
 SCJMapper-V2 - Spectrum page no longer exists

### ISSUE THREAD

**Issue by sutex** [SCToolsfactory/SCJMapper-V2#112]
What is happening with SCJMapper-V2. The Spectrum page no longer exists, is this because Star Citizens dev's implemented Easy Anti Cheat (EAC)

**Comment by bm98** [comment]
It is because they are not transparent about its use, what is forbidden and what they want to allow and what not.
Does not fit with my idea of open software. And besides as I don't accept such SW I cannot further develop and test.
So I refuse to contribute - Point.

**Comment by iNgeon** [comment]
This is truely heartbreaking, this project has been was a life saver for so many of us in the community.
Thank you for all the effort over the years, still hope down the line it gets revived

**Comment by Nyxtorm** [comment]
Hello !

I have lost count of the many hours SCJMapper has saved me to configure my hardware.

@bm98, I understand your point of view and I am very sad to hear that it will no longer be updated. I will continue to use it until it remains compatible with my use. Thank you anyway for offering it to us over the past few years! :)

**Comment by sschukin** [comment]
maaaan that's so sad to hear... and most sadness comes from weird CIG policies. 

Where is the 'community driven' philosophy they pitched in 2012??!


all the best and thank you for this project.. I will try to get a copy of the mapper elsewhere

**Comment by em4joshua** [comment]
I use this exclusively to create my profiles and I would hope to discuss a way to keep the project alive

**Comment by em4joshua** [comment]
> maaaan that's so sad to hear... and most sadness comes from weird CIG policies.
> 
> Where is the 'community driven' philosophy they pitched in 2012??!
> 
> all the best and thank you for this project.. I will try to get a copy of the mapper elsewhere

Maybe we should try to contact them

**Comment by bm98** [comment]
Hi - well contacting CIG most likely will not work at all - think .. some fellows will not make up the argument that the rest of the million is happy with the path choosen. One has to be realistic here :) 
May be at some time the In-Game setup will get some attention (or not). 
That would be the one to ask for anyway - 3rd party contributions only will get attention if they can create $$ for CIG (there are examples out there)

**Comment by iNgeon** [comment]
Just a generic github question. Noticed on most repo's once the dev stops support it now also removes the previously release builds from https://github.com/ProjectName/ProjectName/releases. Is this a dev option or a default now with github ?

**Comment by bm98** [comment]
Not that I know.. there is no "Dev Stops" on Github I know of. The owner may delete the complete repo.
I removed the releases, otherwise someone get's an unsuported binary and if something goes wrong I cannot help at all.
The Last Source archive is complete to build the App anyway - but then the support must come from somewhere else.

**Comment by LordValgor** [comment]
@bm98 Just a note:

I find it odd that you'd drop support so readily for this project, but not clearly voice why. Assuming your statement and feelings are true about EAC, why not voice that to your supporters? Why not clearly state that in all posts regarding this project so that we can then complain to CIG about it? Sure it may never make a difference, but it just seems odd to me that you basically ghosted this project. Deleting the Spectrum page, Deleting the releases, Posting nothing about this in the project's description. I didn't even know this (EAC) was something you were passionate about until I tried to update my SCJM program, and found this obscure issue linked through another more recent issue.

I loved this project, and am very grateful for what you all have done over the years, but I disagree with how this was handled. You dropping support because of EAC is of course perfectly fine, but effectively ghosting the project is odd, and one that I suppose I disagree with.

Anyway, I do wish you all the best, and I too hope things change around EAC with SC in the future.

o7
