### ISSUE TITLE
SC not finding game dir

### ISSUE THREAD

**Issue by MichaGru** [SCToolsfactory/SCJMapper-V2#16]
On my PC, SC 2.2 is not finding the StarCitizen install dir, so the mappings dropdown is not available.
When I enter the path in the settings dialog it also does not save.

It seems that the registry entry you are looking for in SCPath.cs is not set on my PC:
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\App Paths\StarCitizen Launcher.exe

As StarCitizen is working fine for me, I am not sure if this is only my problem or could affect others as well.

The following reg key exists on my PC. A fix could be to try the following registry entry in SCPath.cs in case the "App Paths" registry entry is not there:
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Cloud Imperium Games\StarCitizen Launcher.exe

The trace.log shows:
2014-08-16 14:02:52,071|DEBUG|SCJMapper_V2.SCPath|SCLauncherPath1 - Entry
2014-08-16 14:02:52,071|WARN |SCJMapper_V2.SCPath|SCLauncherPath1 - did not found HKLM - AppPath - Launcher.exe
2014-08-16 14:02:52,071|DEBUG|SCJMapper_V2.SCPath|SCLauncherPath2 - Entry
2014-08-16 14:02:52,071|WARN |SCJMapper_V2.SCPath|SCLauncherPath2 - did not found HKLM - Uninstall - StarCitizen
2014-08-16 14:02:52,071|INFO |SCJMapper_V2.SCDefaultProfile|- Use built in defaultProfile

**Comment by JaPeMo** [comment]
Hi.

First sorry for open this issue but I have this problem.

I try to insert the following path in settings/path.... :

C:\Program Files\Cloud Imperium Games\StarCitizen\Public

And every time that I open SCJMapper do this error:

![captura](https://cloud.githubusercontent.com/assets/22034908/18285175/69d2cb9c-746d-11e6-99f2-e66c16de5812.JPG)

I open windows registry and I don't found:

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\App Paths\StarCitizen Launcher.exe

or 

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Cloud Imperium Games\StarCitizen Launcher.exe

and I don't found SCPath.cs to look paths....

Can you help me?

Thanks and regards!!!!

JaPeMo

**Comment by bm98** [comment]
Hi,

 

first try without giving a path and make sure the Checkmark left to the path field is unchecked – restart SCJmapper.

 

If it does not find it per default try only  the following below and apply the checkmark and restart SCJMapper

 

C:\Program Files\Cloud Imperium Games

 

Read the manual page 19   ;-)  You see it needs the path only before the StarCitizen\public etc. folder

 

It is only in my example that I have installed it in E:\G\StarCitizen  instead of the default C:\Program Files\Cloud Imperium Games

So I need E:\G\StarCitizen  you need  C:\Program Files\Cloud Imperium Games

 

Hope it helps,

Regs

Martin

**Comment by JaPeMo** [comment]
Hi Martin

Without path and check works perfectly. A lot of thanks for your help!!!!

Regards, JaPeMo
