### ISSUE TITLE
Some devices listed as "jsx" rather than "js2" or "js3"

### ISSUE THREAD

**Issue by EmanueleCiriachi** [SCToolsfactory/SCJMapper-V2#31]
Hi,

I have a HOTAS (which is merged as a single virtual device via its own software) and a set of rudder pedals; this always worked well, until today when mapping them to roll axis the pedals ended up being referred to as "jsx", and thus ignored by Star Citizen. It took me a while to figure out what caused the issue.

Is there any reason why the mapper adds a letter-based name to my device, and not a number?

**Comment by wolfrider66** [comment]
This concerns me too as I have the X52 plus the Pro Flight Combat Rudder Pedals. I am very interested in this.

**Comment by EmanueleCiriachi** [comment]
Wolf rider, did you had the same issue yourself or are just concerned it might happen to you?

**Comment by wolfrider66** [comment]
I had some problems that were similar setting up my Pedals on a previous version some time ago, but I have not tried to use them since the last update. If I have time today I will go ahead and set everything up and see if I get the same issue as you.

**Comment by bm98** [comment]
jsx is assigned when the mapper cannot identify the device or if it is set to N.A. - see below.
This is possible if the device numbers have changed (plugged into another port, added a device that is recognized as game device, updated a driver etc.).
First unplug and re-plug the game device and start the mapper again - if this is not solving the issue then go to "Js Reassign" (Quick Guide page 17) and see if your device is still listed and then reassign the jsN number to how SC is numbering it. This can be seen normally  using "Dump Log" BUT right now this is off due to the relocation of files after the last CIG update - same reason why it does not find or update with DUMP (this is a pending issue to be fixed)
But you can find the numbers using the console command:  i_DumpDeviceInformation - this is also somewhere in the Quick Guide (page 17)
Now I hope this helps ...

**Comment by wolfrider66** [comment]
Thanks bm98

**Comment by iNgeon** [comment]
Im trying to help a player with his X52
I believe the joystick plugs into the HOTAS and only shows up as one device ?
Also we cannot see all the bottons etc
Any tips would be welcome

**Comment by bm98** [comment]
Is this about the jsx issue ??? jsx is usually when you never assigned it to a particular number,
use the settings to define it as e.g. js1 - it stores the number in the saved profile an will remember it when loading the map again.
Other than that I don't own a X52 an cannot help here - you may go to the appropr. forum in SC and ask there.
