### ISSUE TITLE
Axis rotation values in SC not read correctly.

### ISSUE THREAD

**Issue by brentglines** [SCToolsfactory/SCJMapper-V2#34]
SC not reading axis rotation inputs correctly, Thrustmaster T- Flight Hotas X

**Comment by brentglines** [comment]
SC Joystick Mapper reads inputs on my Thrustmaster T-Flight Hotas X perfectly.  Pitch, Roll, and Yaw inputs register +/- 1000, and zero in the neutral position.

In SC, it seems like the game is reading inputs as 0-2000.  For yaw for example, full left yaw results in no movement.  Neutral on the control results in uncommanded right yaw.  Right yaw results in faster yaw right.  Same for the two other rotation axis.

Is there a zero input I should be setting for each axis of rotation?

**Comment by bm98** [comment]
In XInput the scale is set by the program that uses the device i.e. mine does set it to +-1000 for anything that is an axis, any other program may assign any range it needs - so the readout can only be compared relatively i.e. what is max and neutral. Some scale it from 0..any number rather than around a center i.e. for thrust. So it seems that SC right now gets your controls not as flight control ones. 
There seems to be people that have it running (google). One thing (obviously) is to NOT set it as PS3 device. Other than that disconnect/reconnect. Try to use the joystick assignment of controls in SC directly and see if this is solving the issue.
Well that is about what I can help...

**Comment by brentglines** [comment]
I restored the joystick defaults in the SC keymapper utility, and when I
assign the yaw and roll functions to my throttle rocker switch and the
left/right deflection on the joystick, I get the exact same behavior.  I
didn't change the pitch control, and that works normally.

I think it's an SC issue, maybe restricted to only some Thrustmaster
T-Flight joysticks.  xml files from other T-Flight owners fail to work for
me as well.  It seems odd that your tool sees things properly with trivial
ease, but SC does not.

You must be uber.  ;)
