### ISSUE TITLE
x56 throttle and analogue sticks

### ISSUE THREAD

**Issue by Jonnehs** [SCToolsfactory/SCJMapper-V2#45]
The x56 throttle and analogue sticks dont seem to bind correctly in game from the XML load.

loading the xml sets it to "throttley" (input2) but the working manual mapping is "y (input2)"

![image](https://cloud.githubusercontent.com/assets/11739441/16895358/c097f504-4b6b-11e6-9330-27f850198c6c.png)

Similarly the axis mapped in the app dont seem to translate to ingame for the mini analogue sticks. 

![image](https://cloud.githubusercontent.com/assets/11739441/16895355/9f0b8ea0-4b6b-11e6-8832-1b1bbb3cdd7c.png)

**Comment by bm98** [comment]
For the throttle - check the Throttle checkbox right of the Assign button and then Assign - to map it like js2_throttley - which is then understood by CryEngine. (instead of js2_y only)

I assume you relate to the 'new' ones with X56 (I only have seen adv. on it).
If the Saitek Software is not interfering and it is detected by the mapping program as i.e. js1_rotx I have no idea why CryEngine is not picking it up. I use v_strafe_longitudinal with js2_roty (but this is a rotary knob) here on the X65 and it works in game. Hard to tell why SC does not see it. May be try to map it in game and see if it is picked up at all by the game.

**Comment by Jonnehs** [comment]
I tried the throttle tickbox and that didnt work either.

The analogue sticks map fine ingame. The axis needs to be reversed for one of them which maps fine through the tool, but the others do not, but can be mapped fine manually.

**Comment by Jonnehs** [comment]
Hm ok I reset everything to blank and mapping the sticks works now, but the throttle looks like the correct binding ingame without the throttle tickbox, but it doesnt work until you rebind it ingame. It doesnt seem to change, but starts working

**Comment by Jonnehs** [comment]
if you export the working version and look at the xml and compare;

<action name="v_throttle_abs">
 <rebind input="js2_y"/>
</action>
  
<action name="v_throttle_abs">
<rebind input="js2_y"   />
</action>

Lets assume game bug? :)

**Comment by bm98** [comment]
Spaces 'should'  not affect the interpretation...
Still strange as with mine SC run with js2_throttly - did not tried the pure js2_y (may be later I will try)
And yes there a quite a number of bugs in the control area of SC...
