### ISSUE TITLE
2.6 Support

### ISSUE THREAD

**Issue by GussyH** [SCToolsfactory/SCJMapper-V2#47]
Tried to load my XML file into 2.6 on the PTU this evening and it gave and error about the XML format.

Is a 2.6 version being worked on?

Cheers!

**Comment by bm98** [comment]
2.6.0i worked here with the current one – there are two more actionmaps that will be added.

but let me check the latest version that is live. On DL right now.

Regs

**Comment by GussyH** [comment]
Thanks mate - much appreciated!

**Comment by bm98** [comment]
Just checked - runs also with 2.6.0j here.
May be you want to load your old one in SCJMapper and save it under a new name and try this one.
There might be a number of actions that are no longer supported and those get cleaned out when saving it as a new file.
Otherwise I would need to get the failed XML file to check it

**Comment by GussyH** [comment]
My file was created with the latest 2.26.0.60 beta. So is generating it again going to do anything different?

**Comment by GussyH** [comment]
Shit I've been an idiot :(

PTU installs in a separate folder and I need to copy my mappings over. So sorry!

**Comment by pyrewyrm** [comment]
Noticed an interesting issue.

Assigning hat switch 2 on X55 to pitch/yaw strafe resulting in dual assignment in 2.6.0k of both pitch/yaw view and pitch/yaw strafe. Worked fine in 2.5. New XML mapping names in 2.6?

Also, noticed that SCJMapper does not recognize/register/indicate the stick on x55 throttle.

**Comment by bm98** [comment]
There were some changes in the profile from 2.5 to 2.6 - don't know if this affect yours.
And yes the stick is not handled as joystick item and therefore the program does not see it.
I think it is either a mouse or nothing (I disabled it on my X65f in the Saitek software otherwise things go crazy...)
