### ISSUE TITLE
V 2.30.0.64 GUI missing missing "Dev Ctrl, Assign and other inputs from mapping section.

### ISSUE THREAD

**Issue by ClaBrown** [SCToolsfactory/SCJMapper-V2#60]
I'm a newbie, sorry if I'm missing the obvious. SCJMapper_QGuide V2.30beta.pdf on pages 4 and 9 show an area labled "Mapping" which includes "Selected", "Mapping", "Dev Ctrl" text boxes and several buttons and a check box with lables "Assign" "Disable" "JS / Kybd" etc. On my screen in that section there are only the "Selected" and "Mapping" text boxes, the rest are missing from "Dev Ctrl" and on down. Since these buttons are used to actually assign functions, I'm not sure exactly how to follow the documentation indicating to "hit the “Assign” button", when there isn't an "Assign" button to hit. 

I have managed to change some functions by right clicking in the "Action Tree" area of the GUI, but most of the functions described in the Mapping section of the Documentation don't seem to be available through that.

Tried to take a screen shot of that area, hope it works:

![scjm_screenshot](https://user-images.githubusercontent.com/33550178/32664741-2b17fafe-c600-11e7-99d9-08bb2cd7216c.jpg)

TIA, Cla

**Comment by bm98** [comment]
Hi Cla,

 

yes there is a lot missing… this is how it should look like

 



 

It might be that this is due to Display Scaling applied (looks like Win10 you have??).

I use Windows Forms to build the application and this does not work well with scaling…

 

You may check the following:

Rightclick on desktop and find the (second last?) entry “Display Settings” or similar (depends on the language)

 

There should be something which includes Size of items and then a % number - where you may see 125% or 150%.

You may change this for a test to 100% and logout and login again and try the application to run and

See if this will make it work.  Though everything is pretty small with 100% setting….

 

So remember your setting to get back to it later (again you may have to logout/login again to make it work with all apps)

 

Right now I don’t have a good workaround other than this.

Win Scaling is changing all the time and it is hard to keep up with them 

 

Regs

**Comment by ClaBrown** [comment]
Ok, more information ... I was looking at SC Joystick Mapper in a window. If I maximize that window I can now see this ...

![scjm_screenshot1](https://user-images.githubusercontent.com/33550178/32669119-777c1c10-c60d-11e7-93e6-4c3560e27b71.jpg)

If I hide the task bar I can see this ....

![scjm_screenshot2](https://user-images.githubusercontent.com/33550178/32669221-c52e8a2e-c60d-11e7-9107-c05479cbcfc3.jpg)

So it looks like some kind of interface sizing problem or resizing problem. My display is at its highest resolution of 1920 x 1024. Windows 7 Pro. In Control Panel > Display, it is set to "Medium 125%," to make it easier to read. I'll try setting it back to 100% and see if that helps ... except it's telling me I have to close everything, so I'll let you know the results after I reboot. I've written a few programs for windows and I know display issues like this can be weird.

**Comment by ClaBrown** [comment]
Ok, more information ... with the display set back to 100%, that area is now visible. But boy is the text small. I can use this as a work around while playing with the joystick settings, but it's a bit tedious reconfiguring the display and rebooting. Kind of reminds me of the good old days ... tweeking config.sys, autoexec.bat and himem.sys, or other memory managers to run games like the original Wing Commander and Privateer ... ha ha. 

There's actually quite a bit of unused space now in the SCJMapper interface. I have fought with display issues like this in various development environments and I know they can be a PITA. Could I suggest a minor display reorganization to spread out the buttons in the Conversions section into a thinner line under the center and right columns or maybe all 3 to simply side step this issue? Sort of like this:

![scjm_screenidea](https://user-images.githubusercontent.com/33550178/32673013-50374d10-c61b-11e7-9c49-448523d06cfc.jpg)

Anyway, appreciate your hard work!!! Thanks, Cla.

**Comment by bm98** [comment]
Glad to see it works .. somehow..
I have to move it to WPF on the long run but first let's see what 3.0 is going to be about mappings.
