### ISSUE TITLE
v2.32.0.66 BETA release?

### ISSUE THREAD

**Issue by MarkAlmighty** [SCToolsfactory/SCJMapper-V2#61]
When I came across SC Joystick Mapper on YouTube (https://www.youtube.com/watch?v=Pqlivl6XHzw), it had a link to the GitHub [releases](https://github.com/SCToolsfactory/SCJMapper-V2/releases) page, and the newest available there is currently v2.30.0.64. I've been trying out a profile I made in SC 3.0.0 ALPHA. I believe my SCJM profile is somehow causing my throttle to max up at seemingly random times. It might be when I push any of various buttons I've assigned to other actions, or even when my hands are completely off any input devices (including keyboard and mouse).

When I returned to the default joystick controls, this behavior stopped (and I was actually able to land without increasing my crime stat rating, LOL).

I see you're working on v2.32.0.66 BETA, which patches for SC 3.0.0 ALPHA. Is there an actual release of that available? I'm trying to figure out GitHub, so please forgive my inexperience.

**Comment by bm98** [comment]
We cannot get the defaultProfile from the game assets anymore (new data packaging p4k format which is not disclosed) neither does it find the location anymore. 
In order to work you may need to enter the path manually. 
BUT the defaultProfile changed for some items and some have been added. So the current mapping might lead to some wrong settings for the PTU 3.0.
However your issue points more to a overlay of your actions with predefined actions from CIG.
You may check which ones are mapped onto the same control by using the second Tab on the right side (App Mappings) and then press any key or button to see what it maps to (green are your's, grey the one from the default profile)
I did an update on the defaultProfile which is a bit better than the one included (see attachment)
Place it into the directory where SCJM is located and it should use it after re-start.
[defaultProfile-PTU3.0.0-V1.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/1511507/defaultProfile-PTU3.0.0-V1.zip)

For the update - I just wanted to wait and see if we get a proper defaultProfile from CIG...
And there is an issue with the mouse assignment that I have to fix.

**Comment by MarkAlmighty** [comment]
Awesome, thanks! I'll try this - hopefully tonight - and report back.

**Comment by MarkAlmighty** [comment]
Placing that defaultProfile.xml seems to have made the difference. No more sudden throttling. I can actually play now. Thanks!
