### ISSUE TITLE
UI ISSUE

### ISSUE THREAD

**Issue by royalbonez** [SCToolsfactory/SCJMapper-V2#63]
Hello first off thank you so much for your great project my button box wouldnt work without it secondly after the most recent update the program UI never actually comes up for viewing one the program has been exe hope this helps thanks

**Comment by bm98** [comment]
Can you check if it is outside of viewing - we had this before ?
Check the config file:
In %USERPROFILE%\AppData\Local\Cassini_(SC_handle)
there should be a folder SCJMapper.exe_Url_<something> and underneath the config folder 2.33.67
where the user.config file is:
open with notepad and see if FormLocation is having out of screenbound numbers.
change them to something like 100,100, same with FormSize should be around 1500,900.

If it is not out of bounds - then you may read the manual page 2 (red section) to enable logging and post/send the logfile with the other information in order to help.

**Comment by iNgeon** [comment]
Okay great, I deleted %USERPROFILE%\AppData\Local\Cassini_(SC_handle) folder and started immediately

**Comment by bm98** [comment]
Good to know - have to see what might set the stored locations / size off.
Not much I do on my own here...

**Comment by iNgeon** [comment]
Okay I got this again here my user.cfg file https://pastebin.com/dDJH3rDa

**Comment by bm98** [comment]
It is when the program is closed _minimized_ - it has a FormLocation of -32000,-32000 which is rather outside of the display and it seems that one cannot bring it back then - happens here too.
I record the last position but then if it is minimized while closing it screws up...
It will be fixed in the next version.

**Comment by royalbonez** [comment]
Lost this in email a while back thanks for the update guys
