### ISSUE TITLE
Can't find SCJMapper.exe

### ISSUE THREAD

**Issue by OWL282820** [SCToolsfactory/SCJMapper-V2#76]
Your project looks fantastic and just what I've been looking for; Unzipped the download but SCJMapper.exe isn't there. Can you help please?

**Comment by bm98** [comment]
It is there .. I just DL and opened the binary package (SCJMapper-V2.37Build72.zip):

![image](https://user-images.githubusercontent.com/7956007/42804956-bd606d9c-89aa-11e8-98cf-6a51508bce8b.png)
and you have to extract the complete package to a disc location in order to have all the files. There is no installation needed. Then may be read a bit in the Guide if you never touched SCJMapper there is some useful information and hints for the usage.
