### ISSUE TITLE
We love your work ! Any upgrade for 3.5 ?

### ISSUE THREAD

**Issue by LeChatFantome** [SCToolsfactory/SCJMapper-V2#83]
We love your work ! Any upgrade for 3.5 ?

As the title says, we greatly appreciate this program for star citizen. We would like to know if you have planned to update for 3.5?

Thank you and good luck for the future
Cat
Maybe in the verse ;3

**Comment by bm98** [comment]
So far it seems to work for 3.5 for all but the Gamepad which has been renamed from xboxpad....
Gamepad support may come but only end of April.

**Comment by iNgeon** [comment]
Great. As a side note, they finally fixed [https://robertsspaceindustries.com/community/issue-council/star-citizen-alpha-3/STARC-61611-Cannot_import_some_controller_mappings](url)
I was able to configure my pp_rebindkeys layout_my_joystick-3v5ptu-fcs in SCJmapper and import into SC without issues so far :-)

**Comment by iNgeon** [comment]
A user i referred to SCJmapper asked me why the program does not clear a key-bind when importing the config from SCJm to SC.
In his case he uses Voice Attack with the HCS voice packs. He tried settings up his key-binds and some items required clearing of existing key-binds in game. A example, when clearing a specific binding in SCJm like "Eject" when importing the config into SC the binding does not get cleared. Perhaps if you get a chance you could have a look at clearing key-binds pls.

**Comment by bm98** [comment]
Re Clear a binding - it is called 'Disable' in SCJM.
Either do it manually or via mass disable - 
Use Menu: Show - Toggle Table
Then may be filter for Keyb.
Check 'Edit Disabled' to allow to change it and then hit 'Disable all Unmapped'
Review and Accept Changes .. Close the table and save as new profile (if something went wrong you may have the old one still available..)
Note: I found that the Disable all Unmapped sometimes needs to be hit a few times to catch all if you sort the columns not along the Action Map (Bug needs to be fixed..)
But this allows to Clear all not manually assigned bindings with the least effort..
(BTW read the manual :-) it is there as well )

**Comment by bm98** [comment]
Re entries with /  need to check it for 3.5 anyway - thanks for letting me know.
I did only a rough check due to time constraints.

**Comment by bm98** [comment]
Re / entry: It is in - only CIG decided to rename it for 3.5 ...
![image](https://user-images.githubusercontent.com/7956007/56030414-13416b80-5d1d-11e9-943f-ca10b23511a7.png)
As you see - using the label text (Menu: Config - Settings  - Profile Language -> English
it is now named "Throttle forward / back" - but the profile.xml name is still "v_strafe_longitudinal" (which it was since the very beginning of the game).
So to match the entries with the CIG setting GUI you may want to use the label names rather than the profile names.

**Comment by LeChatFantome** [comment]
Some function has been renamed: 

`activationMode="double_tap" -> multiTap="2"`

**Comment by bm98** [comment]
Hmm, not really .. the double_tap is the same at least since 2.6 and multi_tap is just one of the attributes of this mode. Still for the mapping XML it needs to be in else it does not work like see this one:

`
<action name="v_eject_cinematic">
  <rebind input="kb1_lalt+l"  ActivationMode="double_tap" multiTap = "2"  />
</action>
`

**Comment by iNgeon** [comment]
Just a side note, 3.6 has hit PTU wave 1&2
There is a new launcher https://install.robertsspaceindustries.com/star-citizen/RSI-Setup-1.2.0.exe
With the new installer the PTU and LIVE now both reside in the root C:\Games\Roberts Space Industries\StarCitizen\*
