### ISSUE TITLE
So if i want to change any mapping in default profile, what the process ???

### ISSUE THREAD

**Issue by Systemac** [SCToolsfactory/SCJMapper-V2#88]
Some keys are assigned by default in the default profile. When I reset, its keys are assigned but in the software I erase them well, by doing the usual procedure, pp_rebindkeys layout_my_xxx I get the keybinding you want but the default keys remain assigned, how to make it so that it is not the case ???

**Comment by bm98** [comment]
Basically pp_rebindkeys only 'overlays' the map to whatever the game thinks its current mapping is.
Therefore I usually cleanup with pp_rebindkeys <ENTER> and then leave the console.
Enter the console again and then use pp_rebindkeys filename. So I am sure to have game defaults and overlay of my file only. 
Same procedure if you make breaking changes in the file - else you map on-top of the current mapping and this leads usually to confusion....
To disable a default you assign a blank instead of e.g. a key for those in the mapping file - so when applying it it will remove the default assignment.
In the tool you choose the action in the tree and hit the disable button - it shows eg. kb1_~ then instead of a key.
You may check the manual page 29 for a bit more information.
BTW I will copy this as answer also into the CIG forum for others to read.

**Comment by Systemac** [comment]
I'm really sorry, I used erasing instead of disabling ... yet it's been doing for two years that I use it ... really sorry for the inconvenience and thank you for the quick answer, soon in the verse!
